openapi: 3.0.3
info:
  title: HiPath Tariffication
  description: Back end API for HiPath Tariffication
  version: 1.0.0
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
servers:
  - url: '/v1'
    description: Main api server v1

tags:
  - name: Tariffication
    description: Tariffication APIs

paths:
  /tariffication:
    get:
      description: 'Returns tariffication objects'
      tags:
        - Tariffication 
      operationId: getTariffication
      parameters:
        - name: subcriber
          required: false
          in: query
          description: 'Subscriber number, to return only his tariffication strings'
          schema:
            type: string
        - name: dateStart
          required: false 
          in: query
          description: 'Date and time from wich to display tariffication strings. Format: YYYY-MM-DD HH:mm:ss. Example: 2020-11-22 12:00:00'
          schema:
            type: string
        - name: dateEnd
          required: false 
          in: query
          description: 'Date and time until wich to display tariffication strings. Format: YYYY-MM-DD HH:mm:ss. Example: 2020-11-22 12:00:00'
          schema:
            type: string
        - name: external
          required: false 
          in: query
          description: 'External number, to return tariffication strings wich contains that number'
          schema:
            type: string
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/TarifficationResponse'
    post:
      description: Creates new tariffication
      tags:
        - Tariffication
      operationId: createTariffication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tariffication'
      responses:
        '201':
          description: Returns resultCode 0 and id of created tariffication, or resultCode not null with error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultCode:
                    type: integer
                  id:
                    type: string
                  message:
                    type: string
                required:
                  - resultCode
  /tariffication/{id}:
    get:
      description: Returns single tariffication by unique id
      tags:
        - Tariffication
      operationId: getSingleTariffication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns resultCode 0 and single tariffication with id specified, or resultCode and error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultCode:
                    type: integer
                  message:
                    type: string                    
                  tariffication:
                    $ref: '#/components/schemas/Tariffication'
                required:
                  - resultCode
    delete:
      description: Deletes tariffication with id specified
      tags:
        - Tariffication
      operationId: deleteTariffication
      parameters:
        - name: id
          required: true
          in: path
          description: 'Tariffication string id'
          schema:
            type: string
      responses:
        '200':
          description: Returns resultCode 0, or not 0 resultCode with error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultCode:
                    type: integer
                  message:
                    type: string
                required:
                  - resultCode

components:
  schemas:
      Tariffication:
        type: object
        properties:
          id:
            type: string
            description: An Unique identificator
          dateTime:
            type: string
            description: 'Date and time. Format: YYYY-MM-DD HH:mm:ss. Example: 2020-11-22 12:00:00'
          duration:
            type: string
            description: 'Call duration'
          subscriber:
            type: string
            description: 'Subscriber number'
          external:
            type: string
            description: 'External number'
          trunk:
            type: string
            description: 'Trunk number'
          direction:
            type: string
            description: 'Call direction'
          exitCode:
            type: string
            description: 'Call exit code'            
        required:
          - dateTime
          - duration
          - subscriber
          - external
          - direction
          
      TarifficationResponse:
        type: object
        properties:
          data:
            type: array
            items:
              $ref: '#/components/schemas/Tariffication'
                
        additionalProperties: false

  responses:
    'TarifficationResponse':
      description: Returns data array of Tariffication objects
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TarifficationResponse'
